Add encoding declaration to the script.
Emit more helpful error message with Python 2.X.

Before:

    $ python japama
      File "japama", line 3
    SyntaxError: Non-ASCII character '\xc2' in file japama on line 3, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

After:

    $ python japama
    Traceback (most recent call last):
      File "japama", line 9, in <module>
        import lib.cmd.show
      File ".../japama/lib/__init__.py", line 1
        lambda: (yield from 0)  # Python >= 3.3 is required
                          ^
    SyntaxError: invalid syntax